### ISSUE TITLE
I can't edit the profile I created

### ISSUE THREAD

**Issue by Cassers** [Railly/tinte#32]
When I hit the edit button, nothing happens

![image](https://github.com/user-attachments/assets/c38f8aa1-1d77-4775-9a02-b324a0472d27)

![image](https://github.com/user-attachments/assets/7e2ba362-a1c0-4e2f-976b-d9ac083a473e)

Something similar happens from the preview:

![image](https://github.com/user-attachments/assets/9ba08c65-3099-4743-8515-024752d3bd59)

![image](https://github.com/user-attachments/assets/335be128-16d7-4f86-b9b3-52e3bbd1ec29)

It changes the screen but I can't edit the theme

As you can see in the console, in the first captures I have an error, but no new one appears (nor any other log) when I click the edit button.

PD: I love your project :D

**Comment by Railly** [comment]
Hey, thanks for the kind words. I've already solve it, thanks to you. Tomorrow I'll release it officially. It's good to have eyes on this kind of bugs. ⭐
